### ISSUE TITLE
Support variable renaming

### ISSUE THREAD

**Issue by GuillaumeTaffin** [mathworks/MATLAB-language-server#18]
I think variable renaming variables is part of the LSP.

My need comes that - in the vscode extension - I failed to rename a local variable and all its references in a m-file.

I am kinda aware that the bigger the scope of the renaming, the harder is the resolution - in case of name duplication that have to be resolved from context. So only supporting renaming in smaller scopes - ie function or file - should already be quite useful as a first step !

Thank you for all the efforts put in this tooling!

**Comment by dklilley** [comment]
Thanks for raising this suggestion! This is something we would like to add in a future release.

**Comment by dklilley** [comment]
Symbol rename support has been added in [v1.2.5](https://github.com/mathworks/MATLAB-language-server/pull/47).
