### ISSUE TITLE
matlab-languager-server cannot support lsp functions in neovim

### ISSUE THREAD

**Issue by Jaehaks** [mathworks/MATLAB-language-server#35]
**Describe the bug**
matlab-languager-server cannot support lsp functions except for linting in neovim.
it detect syntax error every time when I save the file,  but other functions (syntax highlighting, hovering, go to definition , etc..) do not work. 
My configuration is right? 

When I call vim.lsp.buf.hove() , 
I got error like [ textDocument/hover is not supported by any of the servers registerd ]

**To Reproduce**
1) nvim-lspconfig.lua 
![image](https://github.com/mathworks/MATLAB-language-server/assets/26200835/f5537216-edd6-4f53-b6e2-dd5dece034b7)
![image](https://github.com/mathworks/MATLAB-language-server/assets/26200835/5bac4bef-9021-4744-bd57-ad244eee513c)

2) lsp-zero.lua
![image](https://github.com/mathworks/MATLAB-language-server/assets/26200835/617b02b5-1c09-47de-8779-e760f726b933)

3) mason.lua
![image](https://github.com/mathworks/MATLAB-language-server/assets/26200835/919d33db-17ad-4c58-9dbe-8d8625359cfc)

4) nvim-cmp.lua
![image](https://github.com/mathworks/MATLAB-language-server/assets/26200835/f8fabb7d-ea74-4781-8530-ad498bbb0635)

**Expected behavior**

**Screenshots**

**Useful Information**
 - OS Version: Windows 10
 - Language Server Client: matlab-language-server
 - Client Version: nvim-qt v0.2.17
![image](https://github.com/mathworks/MATLAB-language-server/assets/26200835/ebcff5e6-cb59-4103-99af-1a25c611b0e5)

**Additional context**

**Comment by rkmiec** [comment]
`vim.lsp.buf.hover()` method is not supported by this language server.
There are other methods that you can check, such as `vim.lsp.buf.definition()` even though it doesn't always show the correct line in the file.
LSP is not responsible for your syntax highlighting in neovim - it is probably done by treesitter.

Once you call `vim.lsp.buf.definition()` do you get any error? If not, can you paste last few lines of your lsp log (you can open it with `:LspLog` command in neovim).

**Comment by Jaehaks** [comment]
@rkmiec 

I understand, `vim.lsp.buf.definition()` works now.
