### ISSUE TITLE
Can the internal p-codes be open sourced?

### ISSUE THREAD

**Issue by KagaJiankui** [mathworks/MATLAB-language-server#5]
MATLAB language server is a milestone in external editor support of the MATLAB since it provides unprecedented detailed code hinting and auto completions than any other extensions developed before by the community.

I'm enthusiastic about MATLAB programming and wants to contribute in the server development, and add some external debugging support like breakpoints and variable viewer for the LS and VSCode extension if possible. I believe that there are abundant enthusiasts in the community who has also been eagering to make their contributions. Open-sourcing the core part of the language server can provide a huge convenience and progress for the LS development.

**Comment by hamidingit** [comment]
@KagaJiankui Thanks a lot for the support and enthusiasm to contribute! we welcome contributions from the community and we are working towards replacing p-coded artifacts with .m files over time. Please refer for this [blog post](https://blogs.mathworks.com/matlab/2023/04/26/do-you-use-visual-studio-code-matlab-is-now-there-too/) for more information.
