### ISSUE TITLE
Snippet support in neovim?

### ISSUE THREAD

**Issue by Jaehaks** [mathworks/MATLAB-language-server#52]
**Describe the bug**
Matlab extension of vscode supports code completion like function, snippet etc..
[matlab vscode](https://marketplace.visualstudio.com/items?itemName=MathWorks.language-matlab)

But in neovim, It seems that `completionProvider` supports only completion the word  for keyword, function, modules not snippet.
Doesn't it support out of box snippet?

**Comment by dklilley** [comment]
The MATLAB extension for VS Code ships with a [snippet definition](https://github.com/mathworks/MATLAB-extension-for-vscode/blob/main/snippets/matlab.json). I'm not sure whether something similar is possible in Neovim.

However, in v1.3.0 of the language server, snippets are now provided through the `completionProvider` from MATLAB. Please note that this requires MATLAB R2025a, so I would recommend trying out the [R2025a Prerelease](https://www.mathworks.com/downloads/prerelease).

I am going to mark this closed for now, but please feel free to reopen with any comments if you feel this isn't addressed.
